name: Clone to Dev Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Clone:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the dev branch of emojimatch 
        run: |
          git clone --branch dev https://github.com/austinvach/emojimatch

      - name: Set push location to emojimatchdev
        run: |
          git remote set-url --push origin https://austinvach:${{ secrets.PAT }}@github.com/austinvach/emojimatchdev
        working-directory: ./emojimatch

      - name: Fetch updates from emojimatch
        run: |
          git fetch -p https://:${{ secrets.PAT }}@github.com/austinvach/emojimatchdev.git
        working-directory: ./emojimatch

      - name: Push updates to emojimatchdev.
        run: |
          git push https://:${{ secrets.PAT }}@github.com/austinvach/emojimatchdev.git dev
        working-directory: ./emojimatch