name: Clone to Dev Site

on:
  push:
    branches:
      - main

jobs:
  clone_and_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the dev branch of emojimatch 
        run: |
          git clone --branch dev https://github.com/austinvach/emojimatch

      - name: Set push location to emojimatchdev
        run: |
          git remote set-url --push origin https://${{ secrets.PAT }}@github.com/austinvach/emojimatchdev
        working-directory: ./emojimatch

      - name: Fetch updates from emojimatch and push updates to emojimatchdev.
        run: |
          git fetch -p origin
          git fetch -p origin
        working-directory: ./emojimatch