name: Publish to /dev

on:
  workflow_dispatch:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Push to another repository
      run: |
        git remote add new-repo https://github.com/austinvach/emojimatchdev.git
        git push new-repo dev
      env:
        NEW_REPO_TOKEN: ${{ secrets.NEW }}