name: Mirror emojimatch to emdev and setup Node.js

on:
  push:
    branches:
      - main # Adjust this branch name if needed

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout emojimatch repository
        uses: actions/checkout@v2
        with:
          repository: austinvach/emojimatch
          fetch-depth: 0 # Fetch all history for all branches and tags.

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or '17' for Node.js 17

      - name: Mirror to emdev repository
        run: |
          git remote add mirror https://x-access-token:${{ secrets.PAT }}@github.com/austinvach/emdev.git
          git push --mirror mirror