name: Clone to Dev Site

on:
  push:
    branches:
      - main

jobs:
  clone_and_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the dev branch of emojimatch 
        run: |
          git clone --branch dev https://x-access-token:${{ secrets.PAT }}@github.com/austinvach/emojimatch
          cd emojimatch

      - name: Set push location to emojimatchdev
        run: |
          git remote set-url --push origin https://x-access-token:${{ secrets.PAT }}@github.com/austinvach/emojimatchdev

      - name: Fetch updates from emojimatch and push updates to emojimatchdev.
        run: |
          git fetch -p origin
          git push origin dev