name: Mirror to emdev

on:
  push:
    branches:
      - main

jobs:
  clone_and_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone emojimatch 
        run: |
          git clone https://github.com/austinvach/emojimatch.git
          cd emojimatch.git

      - name: Mirror to emdev
        run: |
          git push --mirror https://github.com/austinvach/emdev.git

      - name: Mirror to emdev
        run: |
          cd ..
          rm -rf OLD-REPOSITORY.git