name: Clone to Dev Site

on:
  push:
    branches:
      - main

jobs:
  clone_and_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the dev branch of emojimatch 
        run: |
          git clone --branch dev https://github.com/austinvach/emojimatch

      - name: Set push location to emojimatchdev
        run: |
          git remote set-url --push origin https://github.com/austinvach/emojimatchdev
        working-directory: ./emojimatch

      - name: Fetch updates from emojimatch and push updates to emojimatchdev.
        run: |
          git config --global user.name 'austinvach'
          git config --global user.email 'austinvach@outlook.com'
          git fetch -p origin
          echo "${{ secrets.GITHUB_TOKEN }}" | git push --quiet origin dev
        working-directory: ./emojimatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}