name: Clone, Setup Node.js, and Mirror

on:
  push:
    branches:
      - main

jobs:
  clone_and_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone emojimatch repository
        run: |
          git clone https://github.com/austinvach/emojimatch.git
          cd emojimatch

      # - name: Setup Node.js
      #   run: |
      #     curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      #     sudo apt-get install -y nodejs

      - name: Mirror to emdev repository
        run: |
          git remote add mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/austinvach/emdev.git
          git push --mirror mirror