name: Mirror to emdev

on:
  push:
    branches:
      - main

jobs:
  clone_and_mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Create a bare mirrored clone of emojimatch 
        run: |
          git clone --mirror https://github.com/austinvach/emojimatch.git
          cd emojimatch

      - name: Set push location to emdev
        run: |
          git remote set-url --push origin https://github.com/austinvach/emdev

      - name: Fetch updates and push.
        run: |
          git fetch -p origin
          git push --mirror